### ISSUE TITLE
How to Hide and Show Column Dynamically?

### ISSUE THREAD

**Issue by feiraelectronica** [jbetancur/react-data-table-component#708] opened 2020-10-23 07:58 UTC
Need Help to hide and show columns dynamically. Couldn't find a way to hide and show it by the user. Something like this -

![image](https://user-images.githubusercontent.com/72189108/96971951-703ff380-1548-11eb-9ea2-37e69e55c54f.png)

or this

![Uploading image.png…]()

**Comment by kalinchuk** [comment] 2020-10-26 00:20
I think this is a duplicate of https://github.com/jbetancur/react-data-table-component/issues/703

**Comment by feiraelectronica** [comment] 2020-10-30 03:31
> I think this is a duplicate of #703

just noticed. thank you. if you already have the solution please let me know. really need it. @jbetancur

**Comment by jbetancur** [comment] 2020-11-11 16:04
I've moved #703 as a feature request. This is certainly a bit of a pain, so need to think of a better way to solve this, but in the meantime give this a try:

You could change `columns` into a function that returns a new `columns` and then. has some logic to update the columns you want to omit. If you do this you will need to memoize columns to avoid performance issues.

Click the Story Tab here for a related example:
https://jbetancur.github.io/react-data-table-component/?path=/story/general--optimized-hooks

So, instead of say:

```js
const columns = [...]
```

Try:

```js
const columns = (omitMe) => {
 // you can also try to do a find/update on the columns array by using name as the key
 return [...{..., omit : omitMe}]
}
```
if you use hooks make sure to `useMemo` on the columns function.

**Comment by jbetancur** [comment] 2020-11-11 16:12
Actually, here is a working example. Now that I think about it I am not sure a feature is needed @kalinchuk and @feiraelectronica since with React hooks this is pretty straightforward:

```js
const OmitColumnTable = () => {
  const [hideDirector, setHideDirector] = React.useState(false);

  const columns = React.useMemo(() => [
    {
      name: 'Title',
      selector: 'title',
      sortable: true,
    },
    {
      name: 'Director',
      selector: 'director',
      sortable: true,
      omit: hideDirector,
    },
    {
      name: 'Year',
      selector: 'year',
      sortable: true,
    },
  ], [hideDirector]);

  return (
    <>
      <button onClick={() => setHideDirector(!hideDirector)}>Hide Directory Column</button>
      <DataTable
        title="Movie List"
        columns={columns}
        data={data}
      />
    </>
  );
};
```

**Closed** 2020-11-13 07:51 UTC

**Comment by marcelovani** [comment] 2021-01-28 10:38
I achieved the same but for multiple columns using states.
`const [tableColumns, setTableColumns] = React.useState(getColumns(fields));`

Each item has a callback to a function like this
```
  function toggleColumn(id) {
    let columns=[...tableColumns];
    columns[id].omit = !columns[id].omit;
    setTableColumns(columns);
  } 
```

Items
`<a onClick={() => {toggleColumn(this.props.id)}}>Toggle</a>`

the table is built with states
```
  <DataTable
    columns={tableColumns}
    data={props.data}
  />
```
