### ISSUE TITLE
Total number of records should be changeable.

### ISSUE THREAD

**Issue by prince3339** [jbetancur/react-data-table-component#79] opened 2019-03-21 12:14 UTC
**Is your feature request related to a problem? Please describe.**
Yes. I need to show total number of records from database query. Based on that I'll have to get paginated data from server. Right now it's taking total number of pages from Data length.

**Describe the solution you'd like**
Total number of records should be changeable. There should be props like `NumberOfPages/TotalRecords`

**Describe alternatives you've considered**

**Additional context**

**Comment by jbetancur** [comment] 2019-03-22 21:53
Hello @prince3339,

I'm not completely clear on what you are asking for. Do you just need the callback for Pagination to return the total number of records? Can you give me a workflow or code sample of what you are trying to achieve?

**Comment by prince3339** [comment] 2019-03-22 22:03
In this library, you are setting total page number based on data length. But in my case I don't have all the data in the first place. I know the total records from the query. Say in database there 200 records. I know that number.
Now say, I have set the page limit 20. So in one query/api call I get 20 records. And total page should be Math.ceil(200/20).
Here the problem arises. Instead of Math.ceil(total records(200)/20), you are doing Math.ceil(Data.length/20). So I won't be able to get all my data based on correct pagination.

I hope you understand now.

**Comment by jbetancur** [comment] 2019-03-22 22:22
Yea, I see the issue now. The code assumes that you are paging a fixed row total count, but is not accounting for the case where an actual pagination API query is being performed.

 I'll see about providing a new property.

**Comment by jbetancur** [comment] 2019-03-22 23:24
Ok, I'll be adding a new optional property named `paginationTotalRows` that can be used to override `data.length`.  In addition, onChangePage will return both the current index and total row count so it can also be accessed within that callback.

Thanks for finding this issue @prince3339 . I'll also need to add a new demo for server-side pagination but will do that in a separate issue

**Comment by jbetancur** [comment] 2019-03-22 23:55
Closed by #80

**Closed by jbetancur** 2019-03-22 23:55 UTC
Labels: bug

**Comment by prince3339** [comment] 2019-03-23 10:02
@jbetancur
Thanks for taking this issue seriously.
And I'm happy to contribute 😊 here.

**Comment by jbetancur** [comment] 2019-03-26 16:47
@prince3339 no problem!  Of course, contributions are always welcome! 👍

**Comment by prince3339** [comment] 2019-04-29 21:02
@jbetancur Is it fixed now? I really want to use this library if this issue is resolved.

**Comment by paschaldev** [comment] 2023-09-20 17:28
Coming back to this, I noticed something weird, I use `paginationServer` because my pagination is handled at the bakcend by passing query parameters `?page=2`

When you have a `Datatable` component that is rendered Twice, when the totalRow is updated during re-render, this doesn't reflect in the Datatable component.

In my case, before API call, `Datatable` is rendered to show loading state with `paginationTotalRows={response?.total}`, on first render, `response.total` is `undefined` (App doesn't know total length until after API call).

After API call, `{response?.total}` is 20 but notihing changes in the pagination component, it's disabled. However, if I pass a static number, it works. (This doesn;t fit my use case yet because I need to fetch length from the server first). What could be the cause? ANy help would be appreciated 

@jbetancur
