### ISSUE TITLE
Can not highlight selected row when "striped rows" is selected

### ISSUE THREAD

**Issue by MrAkblt** [jbetancur/react-data-table-component#521] opened 2020-04-06 15:36 UTC
## To Reproduce
1. Go to https://jbetancur.github.io/react-data-table-component/?path=/story/general--kitchen-sink
2. Select highlight selected rows and striped rows
3. Select dark row
4. See not highlighted

**Comment by jbetancur** [comment] 2020-04-06 16:19
I am unable to reproduce this. It may be that the color may not be contrasting well on your screen or perhaps this is cross-browser related? But I have no idea what browser you are using.

It's challenging to help without more detail:

https://github.com/jbetancur/react-data-table-component/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by MrAkblt** [comment] 2020-04-06 17:14
Sorry for missing detail
OS: Manjaro (Arch)
Browser:  Chromium 80.0.3987.149 Arch Linux, Mozilla Firefox 74.0

As seen in the picture, the first selected line is not obvious.

![React-data-table](https://user-images.githubusercontent.com/9157723/78585579-c4041d00-7842-11ea-87b7-d332e826ce88.png)

**Comment by MrAkblt** [comment] 2020-04-07 05:50
Well, thanks for the quick response. Good luck with.

**Comment by jbetancur** [comment] 2020-04-13 03:59
@MrAkblt I totally misunderstood you - it's been a long week. You are correct, this is in fact a styling bug where the striped rows are taking precedence over the selected row. I'll put this in for a 6.7.0 or a 6.7.1 release soon.

**Comment by jbetancur** [comment] 2020-04-13 04:55
@MrAkblt this is now fixed in 6.7.0

**Closed by jbetancur** 2020-04-13 04:55 UTC
Labels: bug

**Comment by MrAkblt** [comment] 2020-04-28 17:18
I have just noticed your comment @jbetancur , thanks for your fix.
