### ISSUE TITLE
Default sorting not working

### ISSUE THREAD

**Issue by Eithcowich** [jbetancur/react-data-table-component#439] opened 2020-01-24 12:08 UTC
I want my table to pre-sort to one of the columns. This is how I set the column: 

        {
          name: 'col name',
          selector: 'colSelector',
          sortable: true,
          defaultSortField: true,
          defaultSortAsc: false,
        },

But the table isn't pre-sorted, and reloading the page doesn't work. What am I missing?

**Comment by impactcolor** [comment] 2020-01-25 23:29
What does the component look like?
What do you mean by “doesn’t work”.

**Comment by rjray** [comment] 2020-01-26 03:04
See [this part of the docs](https://github.com/jbetancur/react-data-table-component#1624-sorting). The `defaultSortField` setting is table-level (that is, you specify it as an attribute to the the `<DataTable>` component). And it takes the name of the row-field (the selector, not the name you've given it) as a value, not a boolean.

**Comment by Eithcowich** [comment] 2020-01-26 15:51
> See [this part of the docs](https://github.com/jbetancur/react-data-table-component#1624-sorting). The `defaultSortField` setting is table-level (that is, you specify it as an attribute to the the `<DataTable>` component). And it takes the name of the row-field (the selector, not the name you've given it) as a value, not a boolean.

Thanks, @rjray. The sorting is on now (the little arrow is on the right column) but it's ascending, and I need it descending. 

This is the relevant element: 

        <DataTable
            defaultSortField="timesLostProposal"
            defaultSortAsc="false"
            persistTableHead="true"
            pagination="true"
            highlightOnHover="true"
            pointerOnHover="true"
            responsive="true"
            dense="false" //can be overridden in the css with rows.denseHeight

            theme="dark"
            title="my title"
            columns={columns}
            data={dataTableData}
        />

While we're at it, how do I calculate fields? In other words if I want something like this: 

        {
          name: 'Winning%',
          selector: '(timesWon / timesLost) * 100',
          sortable: true,
        },

Thanks!

**Comment by rjray** [comment] 2020-01-26 23:19
As it happens, I've had a similar issue to this as well :-).

I found that (to me) the best approach is to pre-compute the data you want. In my case, I have a column of author names. In the database, they're stored as "First Last". But for both displaying and sorting, I wanted "Last, First". So in the component that receives the set of rows from my database (actually JSON data from my node back-end), I transform the "author" key in-place. Then just use "author" as the selector for that column.

In your case above, you might compute the winning average into a completely new column and then reference it in your array of column definitions (and maybe not even bother displaying timesWon and/or timesLost).

**Comment by Eithcowich** [comment] 2020-01-27 07:45
Thanks @rjray, I'll just do it on the server. What about the `asc` vs. `dec`? It's the one I can't without. I tried setting `defaultSortAsc` to false but it stays ascending. 

    <DataTable
        defaultSortField="timesLostProposal"
        defaultSortAsc="false"
        persistTableHead="true"
        pagination="true"
        highlightOnHover="true"
        pointerOnHover="true"
        responsive="true"
        dense="false" //can be overridden in the css with rows.denseHeight

        theme="dark"
        title="my title"
        columns={columns}
        data={dataTableData}
    />

**Comment by rjray** [comment] 2020-01-27 17:16
I'm not sure here, but I THINK the problem is that true/false values need to be passed as JavaScript values, not strings. Try the following:

    <DataTable
        defaultSortField="timesLostProposal"
        defaultSortAsc={false}
        persistTableHead={true}
        pagination={true}
        highlightOnHover={true}
        pointerOnHover={true}
        responsive={true}
        dense={false} //can be overridden in the css with rows.denseHeight

        theme="dark"
        title="my title"
        columns={columns}
        data={dataTableData}
    />

**Comment by Eithcowich** [comment] 2020-01-27 17:57
Yes, putting the value between `{ ... }` does the trick. Thanks! @rjray 

The server side, or on the page column calculations make less sense to me. I'll create a separate issue. Thanks again.

**Comment by jbetancur** [comment] 2020-01-29 03:54
Closing this as resolved - thank you @rjray

**Closed by jbetancur** 2020-01-29 03:54 UTC
