### ISSUE TITLE
Columns Reorder: Be able to move columns around by drag and drop

### ISSUE THREAD

**Issue by javier-brenes-gap** [jbetancur/react-data-table-component#580] opened 2020-05-21 17:13 UTC
## Feature Check list

- [x] Agree to the [Code of Conduct](https://github.com/jbetancur/react-data-table-component/blob/master/CODE-OF-CONDUCT.md)
- [x] Read the README to ensure the feature is not already present
- [x] You read [Creating Issues, Features and Pull Requests](https://github.com/jbetancur/react-data-table-component/issues/387)
- [x] Considered the value versus complexity for all users of the library as well as library maintenance
- [x] Considered if this can be a storybook or documentation example

## Is your feature request related to a problem? Please describe

We want to allow users to set the position of the columns as they want.

## Describe the solution you'd like

Allow columns to be dragged to a specific position within the table and be dropped wherever they want. 

## Describe alternatives you've considered

Add a new property to each column to determine whether it's possible to move it.

**Comment by jbetancur** [comment] 2020-05-27 11:57
Noted. There are a few open feature requests on this already.

**Comment by jbetancur** [comment] 2021-06-23 02:55
This is a dupe of #356

**Closed by jbetancur** 2021-06-23 02:55 UTC
Labels: feature
