### ISSUE TITLE
Expand Selected

### ISSUE THREAD

**Issue by mattredmond** [jbetancur/react-data-table-component#230] opened 2019-09-02 10:00 UTC
I've been trying to develop an Expand Selected Rows feature with your DataTable. I tried using the defaultExpandedField but it did not seem to affect the table upon changing state and re-rendering. I went into the dev code and attempted to force it to use defaultExpandedField, where I discovered that this would stop the ability to toggle those expanded rows using the expandableIcon.

Ideally, I'd like some way to systematically expand rows or just change their state in general but it seems that all of this is handled internally so it might not be possible.

My alternative solution would be to have a boolean prop called "expandSelected" where each row that is currently selected is expanded, and pressing the expandableIcon would deselect the row as well when this prop is set to true.

This has been an incredibly useful component so far, this is just one feature that I feel could be even more useful on future releases.

**Comment by jbetancur** [comment] 2019-09-04 13:36
I'm glad it's been useful! 

I can definitely consider an `expandOnSelected` feature. Though, I'm not sure how I feel about deselecting when collapsing.

I'll need some time to re-consider some of the logic I am using for expanding rows.

**Comment by aCanalez** [comment] 2019-09-07 21:24
Oh this feature sounds awesome 💃

**Comment by jbetancur** [comment] 2020-02-19 13:15
This is a dupe of #218 - I am still trying to get some time to do this, but refer to #218 going forward for updates

**Closed by jbetancur** 2020-02-19 13:15 UTC
Labels: feature
