### ISSUE TITLE
BUG when search

### ISSUE THREAD

**Issue by dflabsdeveloper3** [jbetancur/react-data-table-component#287] opened 2019-10-29 07:24 UTC
## Describe the bug
When performing a search (filtering) from the beginning of the table there is no problem.
But I have detected that when I go on page (example: last page or the last pages) if I do a search I get the following error:

"Uncaught Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop."

I have also detected that if I change "rows per page" to 100 and go to the last page (or one of the last) and do the search, it works without problems.

In summary, the search problem only appears when the "rows per page" are default and I search from the last pages.

## Things to keep in mind:
- I have between 2000 and 5000 rows in the database.
- Rows per page: paginationRowsPerPageOptions = {[20, 50, 100, 500, 1000]}
- I'm not using the search engine provided by this [link.](https://jbetancur.github.io/react-data-table-component/?path=/story/filtering--using-subheader) I'm just using a default <TextField> from material-ui.

`<TextField id="input-search" variant="outlined" type="search" name="search" role="search" placeholder="Search" margin="dense" onKeyPress={(e) => this.handleKeyPress(e)} />`

The handleKeyPress function contains this code:

`
handleKeyPress(event) {
        const data = this.state.data;
        const initData = this.state.initData;

        if(event.which === 13) {
            const inputText = document.getElementById("input-search").value;
            
            let found = data.filter(val =>
                new RegExp(inputText, "i").test(val.id) ||
                new RegExp(inputText, "i").test(val.android_version) ||
                new RegExp(inputText, "i").test(val.phone_model) ||
                new RegExp(inputText, "i").test(val.crash_date) ||
                new RegExp(inputText, "i").test(val.report_id) ||
                new RegExp(inputText, "i").test(val.package_name) ||
                new RegExp(inputText, "i").test(val.serial) ||
                new RegExp(inputText, "i").test(val.app_version_code) ||
                new RegExp(inputText, "i").test(val.app_version_name) ||
                new RegExp(inputText, "i").test(val.brand) ||
                new RegExp(inputText, "i").test(val.product) ||
                new RegExp(inputText, "i").test(val.available_mem_size)
            );
            
            if(inputText.length > 0) {
                this.setState({
                    data: found
                })
            }
            
            if(inputText == "") {
                this.setState({
                    data: initData
                })
            }
        }
    }
`

- I use classes instead of Hooks.

## Versions
- react: 16.9.0
- react-data-table-component": 3.6.0
- @material-ui/core": 4.4.2

**Comment by dflabsdeveloper3** [comment] 2019-10-30 12:53
Hi, 
I'm not using server pagination. I just did a fetch call to get all the data from a URL.

I exported 2000 rows from the fetch in to a .json file, so you don't need to use the fetch function.

And here is the [codesadbox.](https://codesandbox.io/s/react-data-table-xy836)

Thank you.

**Comment by jbetancur** [comment] 2019-11-01 04:36
Ok confirmed - there is a bug there when using `pagination`.

This code in DatTable line 188 might be the culprit. I suspect handleChangePage goes into an infinite loop since the filter is changing the underlying data length

```js
  // for client-side pagination it should navigate back one page when there is only 1 item on the last page and it is removed from the data set
  // as long as there is data and the calculated rows (the rows calculated for the current page slice) are 0
  if (pagination && !paginationServer && data.length > 0 && calculatedRows.length === 0) {
    handleChangePage(currentPage - 1);
  }
```

 This one might take some time to fix.

**Comment by jbetancur** [comment] 2019-11-01 13:14
Ok, I have a fix for this! The table should no longer break when you filter on the last page. 

One minor annoyance that you may notice is that if you filter and then clear then the pagination will leave you in some random page (not really random but it depends what you filtered for). I've been looking for a way to implement a prop to reset pagination to the first page. A few other users have asked for this but I am not sure how best to implement it.

Look for a v3.6.2 shortly!

**Closed** 2019-11-01 13:53 UTC
Labels: bug
