### ISSUE TITLE
Change props do not update

### ISSUE THREAD

**Issue by Angelk90** [jbetancur/react-data-table-component#341] opened 2019-12-02 13:23 UTC
## Describe the bug

I am using i18n on the following component, it happens that when user changes the language,
I have to update the props, but they are not updated.
The props I'm making the changes to are:
- columns
- paginationComponentOptions

## Code Sandbox
https://codesandbox.io/s/react-data-table-sandbox-1xppc

**Comment by jbetancur** [comment] 2019-12-02 14:23
It will not work because you are not updating the state and this having it re-render your updated props. You should be using REACT state for your paginationComponentOptions

**Comment by Angelk90** [comment] 2019-12-02 15:54
@jbetancur:
Been to componentDidUpdate and getDerivedStateFromProps?

**Comment by jbetancur** [comment] 2019-12-02 22:00
Here you go, move paginationComponentOptions to state.

https://codesandbox.io/s/react-data-table-sandbox-jo43e

I'm closing this because it's not a bug.

**Closed by jbetancur** 2019-12-02 22:00 UTC
